#!/bin/bash

echo "Using JAVA_HOME=$JAVA_HOME"
echo "Using TANGO_HOST=$TANGO_HOST"
INSTANCE_NAME="development"
echo "Using INSTANCE_NAME=$INSTANCE_NAME"

JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -server -Xmx1G -Djava.io.tmpdir=../lib/native"

"$JAVA_HOME/bin/java" $JAVA_OPTS -DTANGO_HOST=$TANGO_HOST -Dfile.encoding=UTF-8 -cp "../lib/*" hzg.wpn.tango.camera.webcam.WebCam $INSTANCE_NAME -v4